### ISSUE TITLE
Modificar lista de libros publicados.

### ISSUE THREAD

**Issue by ceoaliongroo** [bblatino/conectados#24]
- [ ] Mostrar enlace hacia el detalle del libro.
![captura de pantalla 2015-02-14 a la s 18 24 43](https://cloud.githubusercontent.com/assets/2622152/6200215/cb8b7afe-b476-11e4-84c3-1d9d737e8327.png)

- [ ] Remover enlace de "Descargar"

**Comment by bbgrupojoven** [comment]
This issue was moved to bblatino/new_library#9
