### ISSUE TITLE
Crear formulario para agregar documento por traducir

### ISSUE THREAD

**Issue by ceoaliongroo** [bblatino/conectados#3]
__escenario:__ el coordinador de traducciones entra al sitio, y presiona el boton de __"Crear documento a traducir"__ y muestra el formulario

__formulario:__
- Nombre documento: 
- copiar texto a traducir (parasha semanal)
- idioma fuente:

__resultado:__ crea un documento en google drive y comparte con (@xanote ) para crear archivo para los traductores.

**Comment by bbgrupojoven** [comment]
This issue was moved to bblatino/new_library#10
