### ISSUE TITLE
Definir palettes 

### ISSUE THREAD

**Issue by ceoaliongroo** [bblatino/conectados#42]
Necessary palettes to define [colore intentions](https://material.angularjs.org/#/Theming/01_introduction)  // Paletas necesarias para definir las [intensiones del color](https://material.angularjs.org/#/Theming/01_introduction)

- [ ] General Department //  Departamento General.
- [ ] Library // Biblioteca
- [ ] Youth Group (Blue, Orange and Green) // Grupo Joven (Azul, Naranja y Verde)

**Comment by bbgrupojoven** [comment]
This issue was moved to bblatino/angular_common#2
