### ISSUE TITLE
How we see the documents in the Library / Biblioteca?

### ISSUE THREAD

**Issue by ceoaliongroo** [bblatino/conectados#55]
@abelardovela, 

I created this issue to everybody could follow the topic.

### How is the library (biblioteca)? 
The design we will see, something similar like this page:
http://devdocs.io/

I'm contacting a designer to soon join we us to the team.

### We manage the articles, books via Google Docs?
Google Drive only will works to storage the articles, books (documents) and edit. For the Translators and Editors in the Spnish Department.

But the General Public only see, search and read the documents from the application (AngularJS Connecting via API Google Drive)

**Comment by bbgrupojoven** [comment]
This issue was moved to bblatino/new_library#2
