### ISSUE TITLE
Interfaz de traducción de documentos

### ISSUE THREAD

**Issue by Xanote** [bblatino/conectados#7]
Modulo para la traducción de documentos online.
Puede ser inicialmente una simple tabla con las cadenas de traducción en una columna y la traducción en otra, junto con la marca de T(traducida), V(Verificada) o A (Aprobada).
El modulo debe tener tres tipos de usuarios:
     TRADUCTORES
      REVISORES
      APROBACION FINAL
El input sería el módulo de documentos a traducir provenientes de la aplicación general de traducción
El output sería una tabla para procesar en la aplicación general de traducción
Para cualquier duda o consulta referencia Xan

**Comment by bbgrupojoven** [comment]
This issue was moved to bblatino/new_library#12
